[versions]
junit-version = "1.2.1"
espresso-core = "3.6.1"

navigation-compose = "2.7.7"
navigation-ktx = "2.7.7"

lifecycle_version = "2.8.4"

[libraries]
corektx = "androidx.core:core-ktx:1.13.1"

navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
navigation-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigation-ktx" }

test-ext = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
test-ui-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
test-ui-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "lifecycle_version" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle_version" }
lifecycle-runtimektx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle_version" }

[bundles]
lifecycle = ["lifecycle-common", "lifecycle-process", "lifecycle-runtimektx"]
navigation = ["navigation-compose", "navigation-ktx"]