[versions]
compose-bom = "2024.08.00"

[libraries]
activity = "androidx.activity:activity-compose:1.9.1"
bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
foundation = { module = "androidx.compose.foundation:foundation", version = "1.7.0-rc01" }
foundation-layout = "androidx.compose.foundation:foundation-layout-android:1.6.8"
animation = { module = "androidx.compose.animation:animation", version = "1.7.0-rc01" }
animation-graphics = { module = "androidx.compose.animation:animation-graphics", version = "1.7.0-rc01" }
ui = { module = "androidx.compose.ui:ui" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version = "1.7.0-rc01" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version = "1.7.0-rc01" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui-util = { module = "androidx.compose.ui:ui-util", version = "1.7.0-rc01" }

material3-core = { module = "androidx.compose.material3:material3", version = "1.3.0-rc01" }
material3-android = { module = "androidx.compose.material3:material3-android", version = "1.3.0-rc01" }
material-icons = { module = "androidx.compose.material:material-icons-extended", version = "1.7.0-rc01" }

[bundles]
foundation = ["foundation", "foundation-layout"]
